files:
  js:
    dir: app/assets
    all: app/assets/**/*.js

  php:
    dir: app
    all: app/**/*.php

  css:
    all: public/css/**/*.css
    dest: public/css

  sass:
    all: public/scss/**/*.scss
    dir: public/scss
    deps:
      - public/vendor/foundation/scss

  tests:
    dir: tests
    js: tests/**/*.js
    php: tests/**/*.php

  tasks:
    options:
      dir: ./scripts/tasks/options/
